//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_maneger
{
    using System;
    using System.Collections.Generic;
    
    public partial class task2
    {
        public int TaskId { get; set; }
        public string title { get; set; }
        public string Tdescription { get; set; }
        public string TStatus { get; set; }
        public Nullable<int> Duedate { get; set; }
        public Nullable<int> USId { get; set; }
    
        public virtual userT2 userT2 { get; set; }
    }
}
