//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_maneger
{
    using System;
    using System.Collections.Generic;
    
    public partial class userT2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userT2()
        {
            this.task2 = new HashSet<task2>();
        }
    
        public int UserId { get; set; }
        public string UName { get; set; }
        public string UPassword { get; set; }
        public string email { get; set; }
        public string urole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task2> task2 { get; set; }
    }
}
